### ISSUE TITLE
  Infinite Status: 'JOB_STATE_FAILED loop' + duplicate tweets on relaunch

### ISSUE THREAD

**Issue by cleterrier** [marcomaroni-github/twitter-to-bluesky#109]
Hi,

I'm using version 0.14.1, I have the following .env (under Intel MacOS):

BLUESKY_USERNAME=christletgo.bsky.social
BLUESKY_PASSWORD=**password**
ARCHIVE_FOLDER=**path**
VIDEO_UPLOAD_RETRIES=10
TWITTER_HANDLES=christlet
IGNORE_VIDEO_ERRORS=1
MIN_DATE=2018-10-25T23:00:00.000Z

and use the 'npm run start_log' command.

Despite the VIDEO_UPLOAD_RETRIES=10 and IGNORE_VIDEO_ERRORS=1, within every batch of post creation (below the daily limit), I usually get into an infinite 'Status: JOB_STATE_FAILED' loop in the log, which corresponds to an XRPCError in the Terminal (sorry I don't have the exact error on hand).

Moreover, if I quit and relaunch the import (quitting terminal, relaunching it, restart with 'npm run start_log'), it restarts the import but duplicates the posts. See for example this post duplicatedd five times over the last days: https://bsky.app/search?q=from%3A%40christletgo.bsky.social+%23BonneMere

I now have an account that is full of duplicates so I will have to nuke it and start fresh for ~30K tweets. Before doing that, I'd like to be sure that the 'Status: JOB_STATE_FAILED' problem is solved. Thank you!

**Comment by marcomaroni-github** [comment]
Hi @cleterrier please could you try with version 0.14.0?

**Comment by cleterrier** [comment]
Hi @marcomaroni-github, I was using 0.12.0 when I started the import (about a month ago) and I had the same problem with both the infinite JOB_STATE_FAILED loop and the duplicate tweets creation. I updated to 0.14.1 on Dec 15, hoping to resolve the problems, but to no avail. Should I nonetheless try with 0.14.0?

**Comment by cleterrier** [comment]
0.14.0 stopped on the following error:

```
/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/xrpc/dist/xrpc-client.js:82
                    throw new types_1.XRPCInvalidResponseError(methodNsid, e, resBody);
                          ^

XRPCInvalidResponseError: The server gave an invalid response and may be out of date.
    at AtpAgent.call (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/xrpc/dist/xrpc-client.js:82:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async main (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/app.js:844:70) {
  error: 'Invalid Response',
  headers: undefined,
  success: false,
  status: 2,
  lexiconNsid: 'app.bsky.video.getJobStatus',
  validationError: ValidationError: Output/jobStatus/progress can not be greater than 100
      at integer (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/lexicon/dist/validators/primitives.js:126:24)
      at validate (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/lexicon/dist/validators/complex.js:13:45)
      at validateOneOf (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/lexicon/dist/validators/complex.js:167:15)
      at object (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/lexicon/dist/validators/complex.js:109:31)
      at validate (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/lexicon/dist/validators/complex.js:23:20)
      at validateOneOf (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/lexicon/dist/validators/complex.js:167:15)
      at object (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/lexicon/dist/validators/complex.js:109:31)
      at validateOneOf (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/lexicon/dist/validators/complex.js:166:15)
      at assertValidOneOf (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/lexicon/dist/validation.js:44:45)
      at assertValidXrpcOutput (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/lexicon/dist/validation.js:32:16),
  responseBody: {
    jobStatus: {
      did: 'did:plc:og2kvr2eqd6so7ixfgjagwxc',
      jobId: 'ctgm0vi0ours72v0dr2g',
      progress: 104,
      state: 'JOB_STATE_ENCODING'
    }
  },
  [cause]: ValidationError: Output/jobStatus/progress can not be greater than 100
      at integer (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/lexicon/dist/validators/primitives.js:126:24)
      at validate (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/lexicon/dist/validators/complex.js:13:45)
      at validateOneOf (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/lexicon/dist/validators/complex.js:167:15)
      at object (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/lexicon/dist/validators/complex.js:109:31)
      at validate (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/lexicon/dist/validators/complex.js:23:20)
      at validateOneOf (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/lexicon/dist/validators/complex.js:167:15)
      at object (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/lexicon/dist/validators/complex.js:109:31)
      at validateOneOf (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/lexicon/dist/validators/complex.js:166:15)
      at assertValidOneOf (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/lexicon/dist/validation.js:44:45)
      at assertValidXrpcOutput (/Users/christo/Desktop/X/twitter-to-bluesky-0.14.0/node_modules/@atproto/lexicon/dist/validation.js:32:16)
}

Node.js v22.11.0
```

I am relaunching it

**Comment by cleterrier** [comment]
After relaunch, I hit the JOB_STATE_FAILED error on another tweet with 0.14.0. Nothing seems to appear in the Terminal, full log:

`> twittertobluesky@0.12.0 start_log
> npx tsc && node app.js >> import.log

(node:9457) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 Video job status: 'already_exists'. Video will not be posted.
Error fetching embed URL card: Timeout
Error fetching embed URL card: request to https://events.tum.de/frontend/index.php?sub=183/ failed, reason: getaddrinfo ENOTFOUND events.tum.de
 Video job status: 'already_exists'. Video will not be posted.
 Video job status: 'already_exists'. Video will not be posted.
 Video job status: 'already_exists'. Video will not be posted.
Error fetching embed URL card: request to https://carrieres.cnrs.fr/ failed, reason: unable to verify the first certificate
 Video job status: 'already_exists'. Video will not be posted.
 Video job status: 'already_exists'. Video will not be posted.
 Video job status: 'already_exists'. Video will not be posted.
Error fetching embed URL card: HTTP error: 429 Too Many Requests
 Video job status: 'already_exists'. Video will not be posted.
 Video job status: 'already_exists'. Video will not be posted.
 Video job status: 'already_exists'. Video will not be posted.
Error fetching embed URL card: HTTP error: 403 Forbidden
 Video job status: 'already_exists'. Video will not be posted.
Error fetching embed URL card: HTTP error: 403 Forbidden
 Video job status: 'video duration (74.07 sec) is longer than the maximum allowed duration (60 sec)'. Video will not be posted.
Error fetching embed URL card: HTTP error: 404 Not Found
Error fetching embed URL card: HTTP error: 403 Forbidden
Error fetching embed URL card: HTTP error: 403 Forbidden
Error fetching embed URL card: HTTP error: 403 Forbidden
Error fetching embed URL card: HTTP error: 403 Forbidden
Error fetching embed URL card: HTTP error: 403 Forbidden
Error fetching embed URL card: HTTP error: 403 Forbidden
`

The import.log says for the problematic tweet:
`Parse tweet id '1700232001502969984'
 Created at 2023-09-08T19:37:52.000Z
 Full text 'EM of the brain at macro scale https://t.co/NZbvPgzv5s'
 JobId: ctgmpea0ours72v0e2ng
 Upload video, attempt: 1
  Status: JOB_STATE_FAILED 
  Status: JOB_STATE_FAILED 
  Status: JOB_STATE_FAILED 
  Status: JOB_STATE_FAILED 
  Status: JOB_STATE_FAILED 
  Status: JOB_STATE_FAILED 
  Status: JOB_STATE_FAILED 
  Status: JOB_STATE_FAILED 
  Status: JOB_STATE_FAILED 
  Status: JOB_STATE_FAILED 
  Status: JOB_STATE_FAILED 
  Status: JOB_STATE_FAILED 
`
and so on.

**Comment by cleterrier** [comment]
btw I found why the log says 0.12 even for the 0.14.0 and 0.14.1 version, it's hardcoded here:
https://github.com/marcomaroni-github/twitter-to-bluesky/blob/591500f3332a4ccddb6cbc63b106330bdf90d60d/package.json#L11

**Comment by marcomaroni-github** [comment]
> btw I found why the log says 0.12 even for the 0.14.0 and 0.14.1 version, it's hardcoded here:
> 
> https://github.com/marcomaroni-github/twitter-to-bluesky/blob/591500f3332a4ccddb6cbc63b106330bdf90d60d/package.json#L3

Yes right I forgot to change the version in the package.json

**Comment by cleterrier** [comment]
Anything I can do to address the bug itself (JOB_STATE_FAILED loop even with a VIDEO_UPLOAD_RETRIES parameter)?

**Comment by YoannUniKS** [comment]
I am getting the same error here, an infinite loop of `JOB_STATE_FAILED`, even after setting `VIDEO_UPLOAD_RETRIES=1`. I am using the last version of the tool, 0.14.2.
