### ISSUE TITLE
XRPCError: This file is too large.

### ISSUE THREAD

**Issue by xPaw** [marcomaroni-github/twitter-to-bluesky#25]
```
XRPCError: This file is too large. It is 1.07MB but the maximum size is 976.56KB.
    at ServiceClient.call (node_modules\@atproto\xrpc\dist\client.js:106:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async PostRecord.create (node_modules\@atproto\api\dist\client\index.js:1644:21)
```

Perhaps skip such files?

**Comment by marcomaroni-github** [comment]
This issue is duplicated #11
