### ISSUE TITLE
XRPCError: missing jobId

### ISSUE THREAD

**Issue by KizGalaxy** [marcomaroni-github/twitter-to-bluesky#28]
```
 Video job status: 'video duration (106.93 sec) is longer than the maximum allowed duration (60 sec)'. Video will be posted as a link
C:\Users\Kiz\Downloads\twitter-to-bluesky-0.7.1\node_modules\@atproto\xrpc\dist\xrpc-client.js:75
                throw new types_1.XRPCError(resCode, error, message, resHeaders);
                      ^

XRPCError: missing jobId
    at AtpAgent.call (C:\Users\Kiz\Downloads\twitter-to-bluesky-0.7.1\node_modules\@atproto\xrpc\dist\xrpc-client.js:75:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (C:\Users\Kiz\Downloads\twitter-to-bluesky-0.7.1\app.js:299:62) {
  error: 'missing jobId',
  headers: {
    'content-length': '57',
    'content-type': 'application/json; charset=UTF-8',
    date: 'Wed, 06 Nov 2024 15:13:42 GMT',
    'strict-transport-security': 'max-age=63072000',
    vary: 'Origin'
  },
  success: false,
  status: 400
}
```

**Comment by marcomaroni-github** [comment]
Unfortunately the APIs are not well documented, but here one should definitely distinguish between blocking bugs like this one and non-blocking bugs like the one about the upload already happened.

**Comment by tibor** [comment]
Had this as well:


```
Parse tweet id '790858184378478592'
 Created at 2016-10-25T10:10:59.000Z
 Full text 'Versteckte Kamera im Kölner Zoo 🐯🐧🐋🐴 https://t.co/3Ot0guK20W'
 Upload video
 Video job status: 'video duration (106.52 sec) is longer than the maximum allowed duration (60 sec)'. Video will be posted as a link
 JobId: 
Saving already imported tweets to tweets_mapping.json
/twitter-to-bluesky-patch-1/node_modules/@atproto/xrpc/dist/xrpc-client.js:75
                throw new types_1.XRPCError(resCode, error, message, resHeaders);
                      ^

XRPCError: missing jobId
    at AtpAgent.call (/twitter-to-bluesky-patch-1/node_modules/@atproto/xrpc/dist/xrpc-client.js:75:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/twitter-to-bluesky-patch-1/app.js:310:62) {
  error: 'missing jobId',
  headers: {
    'content-length': '57',
    'content-type': 'application/json; charset=UTF-8',
    date: 'Sun, 10 Nov 2024 00:47:29 GMT',
    'strict-transport-security': 'max-age=63072000',
    vary: 'Origin'
  },
  success: false,
  status: 400
}
```

**Comment by geekcitadel** [comment]
Currently, it looks like the code has a problem with skipping the  videos that are "too big"

I simply removed the large videos from the folder and was able to continue my import to Bluesky if that helps at all.

**Comment by wlonkly** [comment]
As another option, you can add those tweets to `IGNORE_TWEET_ID` for now, then upload them after this issue is fixed.
