### ISSUE TITLE
Invalid app.bsky.feed.post record

### ISSUE THREAD

**Issue by tibor** [marcomaroni-github/twitter-to-bluesky#31]
I get a new error:

```
Saving already imported tweets to tweets_mapping.json
/twitter-to-bluesky-patch-1/node_modules/@atproto/xrpc/dist/xrpc-client.js:75
                throw new types_1.XRPCError(resCode, error, message, resHeaders);
                      ^

XRPCError: Invalid app.bsky.feed.post record: Record/facets/0/features/0/did must be a valid did
    at AtpAgent.call (/twitter-to-bluesky-patch-1/node_modules/@atproto/xrpc/dist/xrpc-client.js:75:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostRecord.create (/twitter-to-bluesky-patch-1/node_modules/@atproto/api/dist/client/index.js:1282:21)
    at async main (/twitter-to-bluesky-patch-1/app.js:358:40) {
  error: 'InvalidRequest',
  headers: {
    'access-control-allow-origin': '*',
    'cache-control': 'private',
    'content-length': '124',
    'content-type': 'application/json; charset=utf-8',
    date: 'Fri, 08 Nov 2024 23:48:32 GMT',
    etag: 'W/"7c-z/1C1OKT9WTrD/2pGnz1eW9QB9Y"',
    'keep-alive': 'timeout=90',
    'ratelimit-limit': '5000',
    'ratelimit-policy': '5000;w=3600',
    'ratelimit-remaining': '3229',
    'ratelimit-reset': '1731109763',
    'strict-transport-security': 'max-age=63072000',
    vary: 'Authorization, Accept-Encoding',
    'x-powered-by': 'Express'
  },
  success: false,
  status: 400
}

Node.js v21.5.0
```

Any idea whats the reason?

**Comment by marcomaroni-github** [comment]
Do you have any details on the type of tweet it's trying to import? Or could you put the payload of the API call it makes that throws the error here.

**Comment by tibor** [comment]
The response before was like this:
```
Parse tweet id '239737720644186112'
 Created at 2012-08-26T14:55:01.000Z
 Full text '@IFTTT Do you know what would really rock? A personal @ifttt.com address, so that I would get a SMS when amazon pricewatch sends a mail.'
{
  '$type': 'app.bsky.feed.post',
  text: '@IFTTT Do you know what would really rock? A personal @ifttt.com address, so that I would get a SMS when amazon pricewatch sends a mail.',
  facets: [
    {
      '$type': 'app.bsky.richtext.facet',
      index: [Object],
      features: [Array]
    }
  ],
  createdAt: '2012-08-26T14:55:01.000Z'
}
Saving already imported tweets to tweets_mapping.json
```

But I’m not sure if that’s the right tweet, as it says “Saving already imported tweets to tweets_mapping.json” at the last line?

**Comment by marcomaroni-github** [comment]
@tibor my guess is that it is confusing with the @iffttt.com handle, try removing the @ in both or the .com in the second one and try again

**Comment by tibor** [comment]
That was the issue indeed. Thanks!
