### ISSUE TITLE
XRPCError: Wrong type of file. It is application/xml but it must match image/*

### ISSUE THREAD

**Issue by grasshoppermouse** [marcomaroni-github/twitter-to-bluesky#49]
```
/Users/hagen/Documents/Misc/twitterstuff/twitter-to-bluesky/node_modules/@atproto/xrpc/dist/xrpc-client.js:75
                throw new types_1.XRPCError(resCode, error, message, resHeaders);
                      ^

XRPCError: Wrong type of file. It is application/xml but it must match image/*.
    at AtpAgent.call (/Users/hagen/Documents/Misc/twitterstuff/twitter-to-bluesky/node_modules/@atproto/xrpc/dist/xrpc-client.js:75:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostRecord.create (/Users/hagen/Documents/Misc/twitterstuff/twitter-to-bluesky/node_modules/@atproto/api/dist/client/index.js:1282:21)
    at async main (/Users/hagen/Documents/Misc/twitterstuff/twitter-to-bluesky/app.js:581:40) {
  error: 'InvalidMimeType',
  headers: {
    'access-control-allow-origin': '*',
    'cache-control': 'private',
    'content-length': '108',
    'content-type': 'application/json; charset=utf-8',
    date: 'Mon, 11 Nov 2024 18:42:27 GMT',
    etag: 'W/"6c-PxmUOZY4sMzwmZtOcZoWWiGFgfQ"',
    'keep-alive': 'timeout=90',
    'ratelimit-limit': '5000',
    'ratelimit-policy': '5000;w=3600',
    'ratelimit-remaining': '4163',
    'ratelimit-reset': '1731353016',
    'strict-transport-security': 'max-age=63072000',
    vary: 'Authorization, Accept-Encoding',
    'x-powered-by': 'Express'
  },
  success: false,
  status: 400
}

Node.js v20.16.0
```

Last log entry:

```
Parse tweet id '1548871830835867648'
 Created at 2022-07-18T03:26:35.000Z
 Full text 'Great thread by @JoanStrassmann. Years ago I similarly suckered myself and had to yank a Science paper, which I blogged about here:
https://t.co/92EcRGdS0A https://t.co/fqOWwpELKS'
 Clean text 'Great thread by @JoanStrassmann. Years ago I similarly suckered myself and had to yank a Science paper, which I blogged about here:
https://grasshoppermouse.github.io/posts/2015-05-15-im-a-sucker-for-a-good-theory/ https://twitter.com/JoanStrassmann/status/1548432529417326593'
Error fetching oembed: no oembed discovery information available
{
  '$type': 'app.bsky.feed.post',
  text: 'Great thread by @JoanStrassmann. Years ago I similarly suckered myself and had to yank a Science paper, which I blogged about here:\n' +
    'https://grasshoppermouse.github.io/posts/2015-05-15-im-a-sucker-for-a-good-theory/ https://twitter.com/JoanStrassmann/status/1548432529417326593',
  facets: [
    { index: [Object], features: [Array] },
    { index: [Object], features: [Array] }
  ],
  createdAt: '2022-07-18T03:26:35.000Z',
  embed: {
    '$type': 'app.bsky.embed.external',
    external: {
      uri: 'https://grasshoppermouse.github.io/posts/2015-05-15-im-a-sucker-for-a-good-theory/',
      title: "Grasshoppermouse: I'm a sucker for a good theory",
      description: '',
      thumb: [Object]
    }
  }
}
```

**Comment by marcomaroni-github** [comment]
@clemensv it's seem a problem of the oembed call?

**Comment by clemensv** [comment]
@marcomaroni-github Just ran into this. These are SVG pics in the embeddings.

We need to check for those `if ( mimeType.startsWith('image/')  && !mimeType.startsWith('image/svg'))`

**Comment by marcomaroni-github** [comment]
@clemensv ok, I created a branch linked to this bug, you can fix it there, thanks.

**Comment by clemensv** [comment]
> @clemensv ok, I created a branch linked to this bug, you can fix it there, thanks.

It's easier to just do PRs from my fork
