### ISSUE TITLE
Script exits uploading video's over 60 sec

### ISSUE THREAD

**Issue by ivo-toby** [marcomaroni-github/twitter-to-bluesky#50]
When trying to import a video which has a length over 60 seconds the script fails and exits.

```
Parse tweet id '763355427925069824'
 Created at 2016-08-10T12:44:51.000Z
 Full text 'test https://t.co/TF8taUGLoT'
 Upload video
 Video job status: 'video duration (63.05 sec) is longer than the maximum allowed duration (60 sec)'. Video will be posted as a link
 JobId:
Saving already imported tweets to tweets_mapping.json
/home/ivo/twitter-to-bluesky/node_modules/@atproto/xrpc/dist/xrpc-client.js:75
                throw new types_1.XRPCError(resCode, error, message, resHeaders);
                      ^

XRPCError: missing jobId
    at AtpAgent.call (/home/ivo/twitter-to-bluesky/node_modules/@atproto/xrpc/dist/xrpc-client.js:75:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async main (/home/ivo/twitter-to-bluesky/app.js:322:62) {
  error: 'missing jobId',
  headers: {
    'content-length': '57',
    'content-type': 'application/json; charset=UTF-8',
    date: 'Mon, 11 Nov 2024 19:33:56 GMT',
    'strict-transport-security': 'max-age=63072000',
    vary: 'Origin'
  },
  success: false,
  status: 400
}

Node.js v22.11.0
```

**Comment by clemensv** [comment]
What do you think is the right strategy? Skip the upload or clip the video at 60s?

**Comment by clemensv** [comment]
@marcomaroni-github The script should warn and skip. Exiting is ugly and the workaround to set "min_date" is too hard to work around for normal users, IMO.

**Comment by shanselman** [comment]
Agreed. Just hit this after a decade of tweets LOL...skip and move on @marcomaroni-github 

LOVE this utility and THANK YOI for your service

**Comment by ivo-toby** [comment]
Thanks for fixing this so quickly!
