### ISSUE TITLE
Missing did in facet causes fatal XRPCError

### ISSUE THREAD

**Issue by metadaddy** [marcomaroni-github/twitter-to-bluesky#68]
Importing the tweet https://x.com/metadaddy/status/190797695215091712

Output:

```
Parse tweet id '190797695215091712'
 Created at 2012-04-13T13:44:50.000Z
 Full text 'Email from @LinkedIn: "Since 3/13/12, 190 members have started a new job at @Salesforce.com" Find yours http://t.co/Sd8vBn9K'
 Clean text 'Email from @LinkedIn: "Since 3/13/12, 190 members have started a new job at @Salesforce.com" Find yours http://salesforce.com/dreamjob'
Error fetching oembed: no oembed discovery information available
{
  '$type': 'app.bsky.feed.post',
  text: 'Email from @LinkedIn: "Since 3/13/12, 190 members have started a new job at @Salesforce.com" Find yours http://salesforce.com/dreamjob',
  facets: [
    {
      '$type': 'app.bsky.richtext.facet',
      index: [Object],
      features: [Array]
    },
    { index: [Object], features: [Array] }
  ],
  createdAt: '2012-04-13T13:44:50.000Z',
  embed: {
    '$type': 'app.bsky.embed.external',
    external: {
      uri: 'http://salesforce.com/dreamjob',
      title: 'Welcome to the #1 Agent-First Enterprise.',
      description: '',
      thumb: [Object]
    }
  }
}
Saving already imported tweets to tweets_mapping.json
/Users/ppatterson/src/twitter-to-bluesky/node_modules/@atproto/xrpc/dist/xrpc-client.js:75
                throw new types_1.XRPCError(resCode, error, message, resHeaders);
                      ^

XRPCError: Invalid app.bsky.feed.post record: Record/facets/0/features/0/did must be a valid did
    at AtpAgent.call (/Users/ppatterson/src/twitter-to-bluesky/node_modules/@atproto/xrpc/dist/xrpc-client.js:75:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostRecord.create (/Users/ppatterson/src/twitter-to-bluesky/node_modules/@atproto/api/dist/client/index.js:1282:21)
    at async main (/Users/ppatterson/src/twitter-to-bluesky/app.js:581:40) {
  error: 'InvalidRequest',
  headers: {
    'access-control-allow-origin': '*',
    'cache-control': 'private',
    'content-length': '124',
    'content-type': 'application/json; charset=utf-8',
    date: 'Wed, 13 Nov 2024 10:04:11 GMT',
    etag: 'W/"7c-z/1C1OKT9WTrD/2pGnz1eW9QB9Y"',
    'keep-alive': 'timeout=90',
    'ratelimit-limit': '5000',
    'ratelimit-policy': '5000;w=3600',
    'ratelimit-remaining': '3518',
    'ratelimit-reset': '1731493005',
    'strict-transport-security': 'max-age=63072000',
    vary: 'Authorization, Accept-Encoding',
    'x-powered-by': 'Express'
  },
  success: false,
  status: 400
}

Node.js v20.15.1
```

Dumping the entire `postRecord`, I see it has an empty `did` in the first facet:

```
{
  "$type": "app.bsky.feed.post",
  "text": "Email from @LinkedIn: \"Since 3/13/12, 190 members have started a new job at @Salesforce.com\" Find yours http://salesforce.com/dreamjob",
  "facets": [
    {
      "$type": "app.bsky.richtext.facet",
      "index": {
        "byteStart": 76,
        "byteEnd": 91
      },
      "features": [
        {
          "$type": "app.bsky.richtext.facet#mention",
          "did": ""
        }
      ]
    },
    {
      "index": {
        "byteStart": 104,
        "byteEnd": 134
      },
      "features": [
        {
          "$type": "app.bsky.richtext.facet#link",
          "uri": "http://salesforce.com/dreamjob"
        }
      ]
    }
  ],
  "createdAt": "2012-04-13T13:44:50.000Z",
  "embed": {
    "$type": "app.bsky.embed.external",
    "external": {
      "uri": "http://salesforce.com/dreamjob",
      "title": "Welcome to the #1 Agent-First Enterprise.",
      "description": "",
      "thumb": {
        "$type": "blob",
        "ref": {
          "code": 85,
          "version": 1,
          "hash": {
            "0": 18,
            "1": 32,
            "2": 97,
            "3": 40,
            "4": 252,
            "5": 99,
            "6": 73,
            "7": 30,
            "8": 86,
            "9": 152,
            "10": 202,
            "11": 187,
            "12": 5,
            "13": 69,
            "14": 69,
            "15": 213,
            "16": 44,
            "17": 59,
            "18": 126,
            "19": 220,
            "20": 120,
            "21": 57,
            "22": 16,
            "23": 116,
            "24": 75,
            "25": 120,
            "26": 19,
            "27": 242,
            "28": 70,
            "29": 238,
            "30": 212,
            "31": 83,
            "32": 199,
            "33": 147
          }
        },
        "mimeType": "image/jpeg",
        "size": 485103
      }
    }
  }
}
```

It looks like this is due to the `@atproto` facet detection getting confused by `@Salesforce.com\"`.

I added code to handle `InvalidRequest` - I'll submit a PR in a moment.

**Comment by marcomaroni-github** [comment]
Linked to this isse #31

**Comment by metadaddy** [comment]
Never mind - the `InvalidRequest` error was already handled in 7592c990

**Comment by metadaddy** [comment]
In fact, there's no error at all now with this tweet:

```
Parse tweet id '190797695215091712'
 Created at 2012-04-13T13:44:50.000Z
 Full text 'Email from @LinkedIn: "Since 3/13/12, 190 members have started a new job at @Salesforce.com" Find yours http://t.co/Sd8vBn9K'
 Clean text 'Email from @LinkedIn: "Since 3/13/12, 190 members have started a new job at @Salesforce.com" Find yours http://salesforce.com/dreamjob'
Error fetching oembed: no oembed discovery information available
{
  '$type': 'app.bsky.feed.post',
  text: 'Email from @LinkedIn: "Since 3/13/12, 190 members have started a new job at @Salesforce.com" Find yours http://salesforce.com/dreamjob',
  facets: [ { index: [Object], features: [Array] } ],
  createdAt: '2012-04-13T13:44:50.000Z',
  embed: {
    '$type': 'app.bsky.embed.external',
    external: {
      uri: 'http://salesforce.com/dreamjob',
      title: 'Welcome to the #1 Agent-First Enterprise.',
      description: '',
      thumb: [Object]
    }
  }
}
Bluesky post create, URL: https://bsky.app/profile/metadaddy-archive.bsky.social/post/3latbisuwr52x
```
