### ISSUE TITLE
It gets stuck with this error: XRPCError: ArrayBuffer: SharedArrayBuffer is not allowed.

### ISSUE THREAD

**Issue by pokeparadox** [marcomaroni-github/twitter-to-bluesky#73]
Only thing to note is the link to the download is no longer valid if it's trying to decode the Twitter shortener
---------

`Parse tweet id '543719530430996480'
 Created at 2014-12-13T10:50:12.000Z
 Full text 'Flying "DeLorean", Back to the Drawing Board. Downoad .craft for #kerbalspaceprogram 
http://t.co/8MnMMxvGri http://t.co/VopcB3Bcwb'
Saving already imported tweets to tweets_mapping.json
/mnt/Storage/VideoEditing/twitter-to-bluesky-0.10.0/node_modules/@atproto/xrpc/dist/types.js:174
        return new XRPCError(status, undefined, message, headers, { cause });
               ^

XRPCError: ArrayBuffer: SharedArrayBuffer is not allowed.
    at XRPCError.from (/mnt/Storage/VideoEditing/twitter-to-bluesky-0.10.0/node_modules/@atproto/xrpc/dist/types.js:174:16)
    at AtpAgent.call (/mnt/Storage/VideoEditing/twitter-to-bluesky-0.10.0/node_modules/@atproto/xrpc/dist/xrpc-client.js:89:37)
    at async RateLimitedAgent.call (/mnt/Storage/VideoEditing/twitter-to-bluesky-0.10.0/app.js:84:24)
    at async main (/mnt/Storage/VideoEditing/twitter-to-bluesky-0.10.0/app.js:615:52) {
  error: 'Unknown',
  headers: undefined,
  success: false,
  status: 1,
  [cause]: TypeError: ArrayBuffer: SharedArrayBuffer is not allowed.
      at webidl.errors.exception (node:internal/deps/undici/undici:3564:14)
      at webidl.converters.TypedArray (node:internal/deps/undici/undici:3903:29)
      at webidl.converters.BufferSource (node:internal/deps/undici/undici:3942:34)
      at webidl.converters.XMLHttpRequestBodyInit (node:internal/deps/undici/undici:9294:34)
      at webidl.converters.BodyInit (node:internal/deps/undici/undici:9311:32)
      at node:internal/deps/undici/undici:3822:16
      at Object.RequestInit (node:internal/deps/undici/undici:3804:21)
      at new Request (node:internal/deps/undici/undici:9465:34)
      at CredentialSession.fetchHandler (/mnt/Storage/VideoEditing/twitter-to-bluesky-0.10.0/node_modules/@atproto/api/dist/atp-agent.js:182:28)
      at async AtpAgent.call (/mnt/Storage/VideoEditing/twitter-to-bluesky-0.10.0/node_modules/@atproto/xrpc/dist/xrpc-client.js:67:30)
}

Node.js v22.11.0`

**Comment by pokeparadox** [comment]
I have tried it again a few of times and it's the same tweet each time and same error

**Comment by pokeparadox** [comment]
I tried again deleting the tweets_mapping.json and with a rate limit of 5 seconds and to get to exactly the same place and throws the same error.

**Comment by shanselman** [comment]
Same issue here @marcomaroni-github, getting it every month of tweets or so. have only made it to 2008 and have to min_date over each one.

`D:\github\twitter-to-bluesky\node_modules\@atproto\xrpc\dist\types.js:174
        return new XRPCError(status, undefined, message, headers, { cause });
               ^

XRPCError: ArrayBuffer: SharedArrayBuffer is not allowed.
    at XRPCError.from (D:\github\twitter-to-bluesky\node_modules\@atproto\xrpc\dist\types.js:174:16)
    at AtpAgent.call (D:\github\twitter-to-bluesky\node_modules\@atproto\xrpc\dist\xrpc-client.js:89:37)
    at async RateLimitedAgent.call (D:\github\twitter-to-bluesky\app.js:84:24)
    at async main (D:\github\twitter-to-bluesky\app.js:621:52) {
  error: 'Unknown',
  headers: undefined,
  success: false,
  status: 1,
  [cause]: TypeError: ArrayBuffer: SharedArrayBuffer is not allowed.
      at webidl.errors.exception (node:internal/deps/undici/undici:3384:14)
      at webidl.converters.TypedArray (node:internal/deps/undici/undici:3723:29)
      at webidl.converters.BufferSource (node:internal/deps/undici/undici:3762:34)
      at webidl.converters.XMLHttpRequestBodyInit (node:internal/deps/undici/undici:9089:34)
      at webidl.converters.BodyInit (node:internal/deps/undici/undici:9106:32)
      at node:internal/deps/undici/undici:3642:16
      at Object.RequestInit (node:internal/deps/undici/undici:3624:21)
      at new Request (node:internal/deps/undici/undici:9260:34)
      at CredentialSession.fetchHandler (D:\github\twitter-to-bluesky\node_modules\@atproto\api\dist\atp-agent.js:182:28)
      at async AtpAgent.call (D:\github\twitter-to-bluesky\node_modules\@atproto\xrpc\dist\xrpc-client.js:67:30)
}
`

**Comment by shanselman** [comment]
Intersting...EVERY tweet this dies on has a t.co link embedded. I'm only going a week at a time and hitting it constantly. Example https://x.com/shanselman/status/1253176469255143424 with this image embed https://t.co/3IYbdZjmip'

**Comment by shanselman** [comment]
@pokeparadox I think it's twitter itself ratelimiting us...

**Comment by shanselman** [comment]
It's the SharedImageBuffer going into uploadBlob. 

I added this around line 707. Looks like it's when recompressIamgeifNeeded gets called @marcomaroni-github ?

```
                                let newImageBuffer;
                                // Convert SharedArrayBuffer to Buffer if necessary
                                newImageBuffer = Buffer.from(imageBuffer);
                              
                                const blobRecord = await rateLimitedAgent.uploadBlob(newImageBuffer, {
```

**Comment by marcomaroni-github** [comment]
I created a branch where I made the change you suggested @shanselman  but I did it directly in the recompressImageIfNeeded function because it is called in several places and the fix you suggested perhaps did not solve the problem in all cases. You can try in the branch linked to this bug, I tried it and it seems ok but I did a very limited test, if you tell me it is ok you too will merge it into main and release the fix.

cc @pokeparadox
