### ISSUE TITLE
Missing required arguments: archive-folder, bluesky-username, bluesky-password

### ISSUE THREAD

**Issue by cjabradshaw** [marcomaroni-github/twitter-to-bluesky#77]
No matter what I seem to do, I consistently get the following error:

> Missing required arguments: archive-folder, bluesky-username, bluesky-password

Example script run in Terminal (macOS Sequoia 15.1):

`npm run start -- -- --archive-folder '~/Users/xxx/xxx/xx/xx/xx/twitterarchive2024/' --bluesky-username xxxx.bsky.social --bluesky-password xxx-xxx-xxx --twitter-handles xxx --simulate`

**Comment by marcomaroni-github** [comment]
@cjabradshaw try to update npm

**Comment by cjabradshaw** [comment]
Thanks for the quick reply. I already have npm v23.2.0 installed, so that wasn't the problem. However, I called node directly as per the comment thread above, and managed to get it to work. Many thanks!

**Comment by shoelaced** [comment]
Also had to call node directly, but then it worked.

**Comment by marcomaroni-github** [comment]
@clemensv whot do you think?

**Comment by antanij** [comment]
Doing this on WSL. Was getting the same error. Followed this thread and used 
`node app.js --archive-folder="/mnt/c/Users/[..]/OneDrive/Documents/Twitter_archive" --bluesky-username dummy[...].bsky.social --bluesky-password [...] --twitter-handles [...] --simulate --disable-import-reply --api-delay 3000`

Getting error:

```
(node:65395) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/mnt/c/Users/[...]/OneDrive/Documents/x2bsky/twitter-to-bluesky-0.10.0/node_modules/@atproto/xrpc/dist/xrpc-client.js:75
                throw new types_1.XRPCError(resCode, error, message, resHeaders);
                      ^

XRPCError: Invalid identifier or password
    at XrpcClient.call (/mnt/c/Users/[...]/OneDrive/Documents/x2bsky/twitter-to-bluesky-0.10.0/node_modules/@atproto/xrpc/dist/xrpc-client.js:75:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async CredentialSession.login (/mnt/c/Users/[...]/OneDrive/Documents/x2bsky/twitter-to-bluesky-0.10.0/node_modules/@atproto/api/dist/atp-agent.js:257:25)
    at async RateLimitedAgent.call (/mnt/c/Users/[...]OneDrive/Documents/x2bsky/twitter-to-bluesky-0.10.0/app.js:84:24)
    at async main (/mnt/c/Users/[...]/OneDrive/Documents/x2bsky/twitter-to-bluesky-0.10.0/app.js:474:9) {
  error: 'AuthenticationRequired',
  headers: {
    'access-control-allow-origin': '*',
    connection: 'keep-alive',
    'content-length': '77',
    'content-type': 'application/json; charset=utf-8',
    date: 'Sun, 17 Nov 2024 00:18:12 GMT',
    etag: 'W/"4d-98r3hvgolnybv7tgksQiZbSE7Zg"',
    'ratelimit-limit': '30',
    'ratelimit-policy': '30;w=300',
    'ratelimit-remaining': '28',
    'ratelimit-reset': '1731802880',
    vary: 'Accept-Encoding',
    'x-powered-by': 'Express'
  },
  success: false,
  status: 401
}

Node.js v22.11.0
```

**Comment by clemensv** [comment]
This is definitely a weird NPM quirk. The easiest way to circumvent it would probably be a pair of import.bat/import.sh scripts that invoke the compiler as needed and then run app.js directly.

**Comment by ffylin** [comment]
I had the same issue. Calling node directly didn’t fix it for me. I tried using .env and that worked.
