### ISSUE TITLE
AssertionError [ERR_ASSERTION]: protocol mismatch

### ISSUE THREAD

**Issue by iznaut** [marcomaroni-github/twitter-to-bluesky#9]
```
➜  twitter-to-bluesky git:(main) ✗ npm run start_log

> twittertobluesky@0.3.1 start_log
> npx tsc && node app.js > import.log

node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

AssertionError [ERR_ASSERTION]: protocol mismatch
    at Object.request (/Users/izzy/Repos/twitter-to-bluesky/node_modules/follow-redirects/index.js:530:14)
    at Object.get (/Users/izzy/Repos/twitter-to-bluesky/node_modules/follow-redirects/index.js:537:44)
    at /Users/izzy/Repos/twitter-to-bluesky/app.js:51:34
    at new Promise (<anonymous>)
    at resolveShorURL (/Users/izzy/Repos/twitter-to-bluesky/app.js:50:12)
    at cleanTweetText (/Users/izzy/Repos/twitter-to-bluesky/app.js:69:34)
    at main (/Users/izzy/Repos/twitter-to-bluesky/app.js:184:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: 'http:',
  expected: 'https:',
  operator: '=='
}

Node.js v20.18.0
```

Based on what I can tell from the log, it looks like it's failing on this tweet since it's the last one (and doesn't get posted to Bluesky:

```
Parse tweet id '951857441'
 Created at 2008-10-08T21:17:00.000Z
 Full text 'Dtoiders! Come join the pictoblog fun! Draw pictures on your DS and share them with your fellow Dtoiders: http://tinyurl.com/3k9dm2'
```

**Comment by Jay2645** [comment]
I am seeing the same thing. The problem goes back to at least v0.3.1, so my guess is maybe something changed on the backend?

**Comment by marcomaroni-github** [comment]
@Jay2645 they should be two different problems, for the http url resolution problem I made a branch with a possible fix https://github.com/marcomaroni-github/twitter-to-bluesky/tree/9-assertion-protocol-mismatch,  @Jay2645 @iznaut  try it and tell me if it solves the "protocol mismatch" problem

**Comment by paceaux** [comment]
@marcomaroni-github I was going to submit a PR, but I see that you're already working on it. 

I resolved this in the `resolveShorURL` function by checking  if the URL was http / s and then using the appropriate url:

```JavaScript
async function resolveShorURL(url: string): Promise<string> {
    const isHttp = url.startsWith("http://");
    return new Promise<string>((resolve, reject) => {
        if (isHttp) {
            http.get(url, response => {
                resolve(response.responseUrl);
            }).on('error', err => {
                console.warn(`Error parsing url ${url}`);
                resolve(url);
            });
        } else {
            https.get(url, response => {
                resolve(response.responseUrl);
            }).on('error', err => {
                console.warn(`Error parsing url ${url}`);
                resolve(url);
            });
        }
    });
}
```

**Comment by marcomaroni-github** [comment]
@paceaux yes, your solution is very similar to mine, you can check it into the branch https://github.com/marcomaroni-github/twitter-to-bluesky/tree/9-assertion-protocol-mismatch

**Comment by paceaux** [comment]
@marcomaroni-github Nice. 

Not that my opinion matters but... ¿approved?

**Comment by iznaut** [comment]
branch worked for a while, but died on a different issue (see #11 )

great work though!
