### ISSUE TITLE
XRPCError: missing jobId v0.12.0 with Node.js v21.7.2

### ISSUE THREAD

**Issue by jakez** [marcomaroni-github/twitter-to-bluesky#94]
Getting an exception thrown here. Glad to provide any more information you need to resolve this. Thanks.

FYI, had to run `node app.js --archive-folder ~/twitter-archive --bluesky-username jake.cosmic.plumbing --bluesky-password passwd1234 --twitter-handles jakez` to get this to run properly.

```
/Users/jakez/twitter-to-bluesky-0.12.0/node_modules/@atproto/xrpc/dist/xrpc-client.js:75
                throw new types_1.XRPCError(resCode, error, message, resHeaders);
                      ^

XRPCError: missing jobId
    at AtpAgent.call (/Users/jakez/twitter-to-bluesky-0.12.0/node_modules/@atproto/xrpc/dist/xrpc-client.js:75:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/Users/jakez/twitter-to-bluesky-0.12.0/app.js:706:70) {
  error: 'missing jobId',
  headers: {
    'content-length': '57',
    'content-type': 'application/json; charset=UTF-8',
    date: 'Tue, 19 Nov 2024 01:25:39 GMT',
    'strict-transport-security': 'max-age=63072000',
    vary: 'Origin'
  },
  success: false,
  status: 400
}

Node.js v21.7.2
```

**Comment by jakez** [comment]
Ah wait. I now read the documentation more closely. I have added --ignore-video-errors and --video-upload-retries and all good now. I will be helping out with the documentation with a PR on the README here.
